id: P7FCBE252
initial_creation_type: input
source_metadata:
  title: Śāntigarbha
  language: bo
  description: 'Texts by and about Śāntigarbha (zhi ba''i snying po), renowned as
    one of the eight vidyādharas of India:'
  volume:
    6ab42163e77f416bbbe3861169164257:
      title: A Praise to the Lotus King
      parent: Praise
created_at: '2022-03-01T02:23:34.706542'
last_modified_at: '2022-03-01T02:23:34.706545'
